#ifndef MAIN_DEFINE_H
#define MAIN_DEFINE_H

// WiFi credentials
#define WIFI_SSID "Wifi T4"
#define WIFI_PASSWORD "Selex2024"

// MQTT Broker information
#define MQTT_SERVER "hub-uat.selex.vn"
#define MQTT_PORT 8883 // Cổng cho kết nối SSL

// Đường dẫn tới file certificate và key
#define CERTIFICATE "-----BEGIN CERTIFICATE-----\n" \
"MIIDpTCCAo2gAwIBAgIUYDPbEvFG0AC6XPlAEE7wQMrmUQgwDQYJKoZIhvcNAQE\n" \
"LBQAwYTELMAkGA1UEBhMCVk4xCzAJBgNVBAgMAkhOMQswCQYDVQQHDAJITjEOMA\n" \
"wGA1UECgwFU2VsZXgxDDAKBgNVBAsMA0lPVDEaMBgGA1UEAwwRc2VsZXgtdWF0L\n" \
"cm9vdC1jYTAeFw0yNDA0MDIxMTA1NTgaFw0yMTQwMzA5MTEwNTU4WjBhMQswCQY\n" \
"DVQQGEwFWTjELMAkGA1UECAwCSG4xCzAJBgNVBAcMAkhOMQwwCgYDVQQKDANTRW\n" \
"xleDELMAkGA1UECwwCSU9UMR4wHAYDVQQDDBVzbGV4LXVhdC1yb290LWNhMCIB\n" \
"IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAycRzmRvcq/nFGwg6tAyJf3E\n" \
"TQX7aOPBYS2TUEm3ZrLCjfnie3GtDYFWL9y9/QbZWknuRojB6fU263UO4cAqDM\n" \
"NxNGnoXCVod7Qdz+0GVOKGF+zF4hab/XZ4SrQx7G9oILBEyOaJvLNhvZ6AfGNg\n" \
"XRxSXVE0CkpyTb3Th+dF/buTNDgl0zMyoQkOPrrQs6ECUMZK6+LEY+Ncvyg6OFK\n" \
"QMU44w7IGHirBVAMeoC+8Eht+9fEmthd44GDSTpBND929zrJLkXFHeRiClbuLrM\n" \
"2k1tSu8j0gMqNTnlKy7A5x6XPpvZ+vSCGFXLII3x7tN09uubpc/jRmEygiFn7fU\n" \
"VAreWQIDAQABo1MwUTAdBgNVHQ4EFgQUn3vW6GcgicPSJ/otwIY4fS0B+ywwHwY\n" \
"DVR0jBBgwFoAUn3vW6GcgicPSJ/otwIY4fS0B+ywwDwYDVR0TAQH/BAUwAwEB/z\n" \
"ANBgkqhkiG9w0BAQsFAAOCAQEAiAvU7ICqg1DlZM27dmgF/rhA2WWOTGnQCZfeT\n" \
"PqxNOChJ4CHxFYTjzStOrO/d6xbLJRET8zx17JKDaX2gs0QaFsseIjbWn2QdCbj\n" \
"WXZryqfQbt2+dGT+xR78lIrej1Tt5KRMWoae3EOEpobR0O8mq8Px/OC14PA1Oj5\n" \
"QMPTQiailSy668Z1bQW80WDsxStD19XrIjQvPoIscMBILQ2To6y7aieUJzBgTpb\n" \
"fFJu8hlRaf+UCJ+bvQNLBxmfszz0sMPvWGHSCStBlPl9DrDQ3eSxTW6fvkdMjKA\n" \
"OP9XuSiS/PjkzEiCM6K3zCXH+GYBP2ZyZ4+T+vtCyfqaCm7i8rizw==\n" \
"-----END CERTIFICATE-----\n"
#define CLIENT_CERTIFICATE "-----BEGIN CERTIFICATE-----\n" \
"MIID0TCCArmgAwIBAgIIejd6t8HTbXwwDQYJKoZIhvcNAQELBQAwYTELMAkGA1U\n" \
"EBhMCVk4xCzAJBgNVBAgMAkhOMQswCQYDVQQHDAJITjEOMAwGA1UECgwFU2VsZX\n" \
"gxDDAKBgNVBAsMA0lPVDEaMBgGA1UEAwwRc2VsZXgtdWF0LXJvb3QtY2EwHhcNM\n" \
"jQxMDIxMDcxNzA3WhcNMzQxMDE5MDcxNzA3WjAcMRowGAYDVQQDDBFjaHV5ZW5f\n" \
"N2wxMHB2NzBicTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPmCJYR\n" \
"6AaoTUV4wfEUEBcugApvqiTOH8AO8l7j6Tw4yQvH3dt+2y+0qn2ar3i9iCDb6HS\n" \
"o2KN68ImDOBNe19YB6HU7cwqg97JqW1+/50nl0D8S/j1EDzZ9RRqKyT+XnyWBL+\n" \
"kRKzxaCrxZRhgRzkCKczgARTO7wxC3zuK5pAi2RYATGBxu0Sq/N2wF3WwKTaSIB\n" \
"3z+eDPmG/87NJOd3j5NFk99jkbHx52OJyWbyPAQkbtIpr7diQjSmM9+Bikp8Q2+\n" \
"R3B7qaGX5W5FScewwNOaEpeOmJ9J/GMjJOIhc8WH/fzVj73UFDKPVgGokP+irto\n" \
"zDfj85S0IEi/vdJ/K9+cMCAwEAAaOB0TCBzjAMBgNVHRMBAf8EAjAAMIGeBgNVH\n" \
"SMEgZYwgZOAFJ971uhnIInD0if6LcCGOH0tAfssoWWkYzBhMQswCQYDVQQGEwJW\n" \
"TjELMAkGA1UECAwCSE4xCzAJBgNVBAcMAkhOMQ4wDAYDVQQKDAVTZWxleDEMMAo\n" \
"GA1UECwwDSU9UMRowGAYDVQQDDBFzZWxleC11YXQtcm9vdC1jYYIUYDPbEvFG0A\n" \
"C6XPlAEE7wQMrmUQgwHQYDVR0OBBYEFJqNwJTYS4q1OitAFqRFsEuhY+BmMA0GC\n" \
"SqGSIb3DQEBCwUAA4IBAQA4hdudith4nZLnryCvZ8saPl1LiwHjLAppYBR+MPMy\n" \
"W2Bgj5sY7sFk8nrjH5hYLjhHyunHZupHTxM5xjpCBGy7hoodjjZZYVNrkH9LeXs\n" \
"6swvYkr/I8//s1xEQfQsgBYgBi9efoH8E/A+q5ZodUgNi6EG5wGTfoHmJe4lTg4\n" \
"rU7An5X+2WPT1SDh6V5HUV0oW4i+XCKE0ndaCIyubw7Hj6Sczwo+hsy9srV22di\n" \
"7KTDxodOVzNifEmKJ60tSD6xVPuXOOME7PHpDZbTZp2eV8uxcUyuBCBcOcfVYRI\n" \
"5NclUDho02FPqjuQHnkkYjjM0i4z94R80Eq2SuPrrEE16Yp5\n" \
"-----END CERTIFICATE-----\n"
#define PRIVATE_KEY "-----BEGIN CERTIFICATE-----\n" \
"MIID0TCCArmgAwIBAgIIejd6t8HTbXwwDQYJKoZIhvcNAQELBQAwYTELMAkGA1U\n" \
"EBhMCVk4xCzAJBgNVBAgMAkhOMQswCQYDVQQHDAJITjEOMAwGA1UECgwFU2VsZX\n" \
"gxDDAKBgNVBAsMA0lPVDEaMBgGA1UEAwwRc2VsZXgtdWF0LXJvb3QtY2EwHhcNM\n" \
"jQxMDIxMDcxNzA3WhcNMzQxMDE5MDcxNzA3WjAcMRowGAYDVQQDDBFjaHV5ZW5f\n" \
"N2wxMHB2NzBicTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPmCJYR\n" \
"6AaoTUV4wfEUEBcugApvqiTOH8AO8l7j6Tw4yQvH3dt+2y+0qn2ar3i9iCDb6HS\n" \
"o2KN68ImDOBNe19YB6HU7cwqg97JqW1+/50nl0D8S/j1EDzZ9RRqKyT+XnyWBL+\n" \
"kRKzxaCrxZRhgRzkCKczgARTO7wxC3zuK5pAi2RYATGBxu0Sq/N2wF3WwKTaSIB\n" \
"3z+eDPmG/87NJOd3j5NFk99jkbHx52OJyWbyPAQkbtIpr7diQjSmM9+Bikp8Q2+\n" \
"R3B7qaGX5W5FScewwNOaEpeOmJ9J/GMjJOIhc8WH/fzVj73UFDKPVgGokP+irto\n" \
"zDfj85S0IEi/vdJ/K9+cMCAwEAAaOB0TCBzjAMBgNVHRMBAf8EAjAAMIGeBgNVH\n" \
"SMEgZYwgZOAFJ971uhnIInD0if6LcCGOH0tAfssoWWkYzBhMQswCQYDVQQGEwJW\n" \
"TjELMAkGA1UECAwCSE4xCzAJBgNVBAcMAkhOMQ4wDAYDVQQKDAVTZWxleDEMMAo\n" \
"GA1UECwwDSU9UMRowGAYDVQQDDBFzZWxleC11YXQtcm9vdC1jYYIUYDPbEvFG0A\n" \
"C6XPlAEE7wQMrmUQgwHQYDVR0OBBYEFJqNwJTYS4q1OitAFqRFsEuhY+BmMA0GC\n" \
"SqGSIb3DQEBCwUAA4IBAQA4hdudith4nZLnryCvZ8saPl1LiwHjLAppYBR+MPMy\n" \
"W2Bgj5sY7sFk8nrjH5hYLjhHyunHZupHTxM5xjpCBGy7hoodjjZZYVNrkH9LeXs\n" \
"6swvYkr/I8//s1xEQfQsgBYgBi9efoH8E/A+q5ZodUgNi6EG5wGTfoHmJe4lTg4\n" \
"rU7An5X+2WPT1SDh6V5HUV0oW4i+XCKE0ndaCIyubw7Hj6Sczwo+hsy9srV22di\n" \
"7KTDxodOVzNifEmKJ60tSD6xVPuXOOME7PHpDZbTZp2eV8uxcUyuBCBcOcfVYRI\n" \
"5NclUDho02FPqjuQHnkkYjjM0i4z94R80Eq2SuPrrEE16Yp5\n" \
"-----END CERTIFICATE-----\n"

// Client ID
#define CLIENT_ID "chuyen"

// User&pasword
#define MQTT_USER "selex"
#define MQTT_PASSWORD "selex"

//Topic
#define MQTT_TOPIC "temp"

#endif // MAIN_DEFINE_H
